name: Run Telegram Bot 24/7
on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: |
          while true; do
            python bot.py || echo "Bot crashed, restarting..."
            sleep 10
          done
